// Embed packages/runtime/runtime.js as a C source file that defines
//   const char nxjs_runtime_js[];      // NUL-terminated UTF-8 source
//   const unsigned int nxjs_runtime_js_len;
//
// This replaces the old QuickJS `qjsc` bytecode step (source/runtime.c).
// V8 evaluates the runtime from source at boot (a startup snapshot is a
// possible Phase 3 optimization).
//
// Usage: node tools/embed-runtime.mjs <input.js> <output.c>

import { readFileSync, writeFileSync } from 'node:fs';

const [, , inPath, outPath] = process.argv;
if (!inPath || !outPath) {
	console.error('usage: embed-runtime.mjs <input.js> <output.c>');
	process.exit(1);
}

const src = readFileSync(inPath); // Buffer (raw UTF-8 bytes)

// Emit as an array of bytes (robust against embedded quotes/newlines/NULs),
// NUL-terminated so it can be used as a C string. Chunked for compiler sanity.
const parts = [];
parts.push('// Auto-generated by tools/embed-runtime.mjs. Do not edit.');
parts.push('const unsigned char nxjs_runtime_js[] = {');

const bytes = [];
for (let i = 0; i < src.length; i++) bytes.push(src[i]);
bytes.push(0); // NUL terminator

let line = '';
const out = [];
for (let i = 0; i < bytes.length; i++) {
	line += bytes[i] + ',';
	if (line.length >= 100) {
		out.push(line);
		line = '';
	}
}
if (line) out.push(line);
parts.push(out.join('\n'));
parts.push('};');
// Length excludes the NUL terminator (matches strlen()).
parts.push(`const unsigned int nxjs_runtime_js_len = ${src.length};`);
parts.push('');

writeFileSync(outPath, parts.join('\n'));
console.error(
	`embedded ${inPath} (${src.length} bytes) -> ${outPath}`,
);
