name: CI

on:
  push:
    branches:
      - main
    tags:
      - '!*'
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/tootallnate/pacman-packages@sha256:c2d614c77f1ca8c494a6498e34923805a53bdc016cfd27756b782b551c0a15c0
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.5.0

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build dependent packages
        working-directory: packages/runtime
        run: pnpm build

      - name: Bundle `runtime.js`
        run: pnpm bundle

      - name: Build `nxjs.nro`
        run: make V=1

      - uses: actions/upload-artifact@v4
        with:
          name: nxjs.nro
          path: nxjs.nro

      - uses: actions/upload-artifact@v4
        with:
          name: nxjs.nsp
          path: |
            build/exefs/
            romfs/
            icon.jpg
            nxjs.nacp

  release:
    name: Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download `nxjs.nro`
        uses: actions/download-artifact@v4
        with:
          name: nxjs.nro

      - name: Download `nxjs.nsp`
        uses: actions/download-artifact@v4
        with:
          name: nxjs.nsp

      - name: Fetch git tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.8

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm build

      - name: Copy `nxjs.nro` to "@nx.js/nro"
        run: cp -v nxjs.nro packages/nro/dist

      - name: Copy files to "@nx.js/nsp"
        run: cp -rv build/exefs romfs nxjs.nacp icon.jpg packages/nsp

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release (if published happened)
        if: steps.changesets.outputs.published == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { createRelease } = await import('${{ github.workspace }}/.github/scripts/create-release.mjs')
            await createRelease({ github, context })
